"""original

Revision ID: 96c6a9900c30
Revises: 
Create Date: 2021-01-07 19:03:12.870616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c6a9900c30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joueur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=9), nullable=True),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=2), nullable=True),
    sa.Column('grandeur', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('equipe', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joueur_age'), 'joueur', ['age'], unique=False)
    op.create_index(op.f('ix_joueur_alias'), 'joueur', ['alias'], unique=True)
    op.create_index(op.f('ix_joueur_equipe'), 'joueur', ['equipe'], unique=False)
    op.create_index(op.f('ix_joueur_grandeur'), 'joueur', ['grandeur'], unique=False)
    op.create_index(op.f('ix_joueur_nom'), 'joueur', ['nom'], unique=False)
    op.create_index(op.f('ix_joueur_position'), 'joueur', ['position'], unique=False)
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('poolers', sa.String(length=256), nullable=True),
    sa.Column('creation', sa.Date(), nullable=True),
    sa.Column('selectionneur', sa.String(length=64), nullable=True),
    sa.Column('statut', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_name'), 'pool', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('joueur_alias', sa.String(length=9), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['joueur_alias'], ['joueur.alias'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_pool_name'), table_name='pool')
    op.drop_table('pool')
    op.drop_index(op.f('ix_joueur_position'), table_name='joueur')
    op.drop_index(op.f('ix_joueur_nom'), table_name='joueur')
    op.drop_index(op.f('ix_joueur_grandeur'), table_name='joueur')
    op.drop_index(op.f('ix_joueur_equipe'), table_name='joueur')
    op.drop_index(op.f('ix_joueur_alias'), table_name='joueur')
    op.drop_index(op.f('ix_joueur_age'), table_name='joueur')
    op.drop_table('joueur')
    # ### end Alembic commands ###
