"""ajout json

Revision ID: bcaa32b51ec8
Revises: 96c6a9900c30
Create Date: 2021-08-07 08:09:30.706899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcaa32b51ec8'
down_revision = '96c6a9900c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joueur', sa.Column('info', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('joueur', 'info')
    # ### end Alembic commands ###
